In [1]:
import pandas as pd
dict = {"keys" : ["k1", "k2", "k3"],
         "names":["john", "ben", "david"],
         "houses":["red", "blue", "green"],
         "grades":["3rd", "8th", "9th"]}
df = pd.DataFrame(dict)
print(df)
print(df.pivot(index="keys", columns="names", values="houses"))#rows converted into columns

  keys  names houses grades
0   k1   john    red    3rd
1   k2    ben   blue    8th
2   k3  david  green    9th
names   ben  david john
keys
k1      NaN    NaN  red
k2     blue    NaN  NaN
k3      NaN  green  NaN

In [4]:
import pandas as pd
dict = {
         "names":["john", "ben", "david"],
         "houses":["red", "blue", "green"],
         "grades":["3rd", "8th", "9th"]}
df = pd.DataFrame(dict)
print(df)
print(pd.melt(df,id_vars=["names"],value_vars=["houses","grades"]))

   names houses grades
0   john    red    3rd
1    ben   blue    8th
2  david  green    9th
   names variable  value
0   john   houses    red
1    ben   houses   blue
2  david   houses  green
3   john   grades    3rd
4    ben   grades    8th
5  david   grades    9th

In [1]:
import pandas as pd

data = {
    "Order_ID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],
    "Date": [
        "2026-01-05","2026-01-08","2026-01-12","2026-01-15","2026-02-03",
        "2026-02-07","2026-02-15","2026-02-20","2026-03-02","2026-03-10",
        "2026-03-15","2026-03-22","2026-04-05","2026-04-10","2026-04-18",
        "2026-05-02","2026-05-09","2026-05-20","2026-06-01","2026-06-15"
    ],
    "Region": [
        "North","South","East","West","North",
        "South","East","West","North","South",
        "East","West","North","South","East",
        "West","North","South","East","West"
    ],
    "Salesperson": [
        "Aman","Rohit","Neha","Karan","Aman",
        "Rohit","Neha","Karan","Aman","Rohit",
        "Neha","Karan","Aman","Rohit","Neha",
        "Karan","Aman","Rohit","Neha","Karan"
    ],
    "Category": [
        "Laptop","Mobile","Laptop","Tablet","Mobile",
        "Laptop","Tablet","Mobile","Laptop","Tablet",
        "Mobile","Laptop","Tablet","Mobile","Laptop",
        "Tablet","Mobile","Laptop","Tablet","Mobile"
    ],
    "Product": [
        "HP 15","iPhone 14","Dell Inspiron","iPad","Samsung S24",
        "Lenovo IdeaPad","Samsung Tab","OnePlus 12","MacBook Air","iPad",
        "Pixel 9","HP 15","iPad","Samsung S24","Dell Inspiron",
        "Samsung Tab","OnePlus 12","MacBook Air","iPad","Pixel 9"
    ],
    "Quantity": [2,3,1,4,5,2,3,4,1,2,3,2,5,4,2,3,5,1,4,3],
    "Sales": [120000,180000,65000,160000,250000,110000,90000,160000,95000,80000,
              210000,130000,200000,240000,130000,95000,225000,100000,180000,210000],
    "Profit": [18000,27000,9000,22000,35000,16000,12000,24000,15000,11000,
               30000,19000,28000,36000,20000,14000,32000,17000,26000,30000]
}

df = pd.DataFrame(data)
df

,Order_ID,Date,Region,Salesperson,Category,Product,Quantity,Sales,Profit
0,101,2026-01-05,North,Aman,Laptop,HP 15,2,120000,18000
1,102,2026-01-08,South,Rohit,Mobile,iPhone 14,3,180000,27000
2,103,2026-01-12,East,Neha,Laptop,Dell Inspiron,1,65000,9000
3,104,2026-01-15,West,Karan,Tablet,iPad,4,160000,22000
4,105,2026-02-03,North,Aman,Mobile,Samsung S24,5,250000,35000
5,106,2026-02-07,South,Rohit,Laptop,Lenovo IdeaPad,2,110000,16000
6,107,2026-02-15,East,Neha,Tablet,Samsung Tab,3,90000,12000
7,108,2026-02-20,West,Karan,Mobile,OnePlus 12,4,160000,24000
8,109,2026-03-02,North,Aman,Laptop,MacBook Air,1,95000,15000
9,110,2026-03-10,South,Rohit,Tablet,iPad,2,80000,11000
10,111,2026-03-15,East,Neha,Mobile,Pixel 9,3,210000,30000
11,112,2026-03-22,West,Karan,Laptop,HP 15,2,130000,19000
12,113,2026-04-05,North,Aman,Tablet,iPad,5,200000,28000
13,114,2026-04-10,South,Rohit,Mobile,Samsung S24,4,240000,36000
14,115,2026-04-18,East,Neha,Laptop,Dell Inspiron,2,130000,20000
15,116,2026-05-02,West,Karan,Tablet,Samsung Tab,3,95000,14000
16,117,2026-05-09,North,Aman,Mobile,OnePlus 12,5,225000,32000
17,118,2026-05-20,South,Rohit,Laptop,MacBook Air,1,100000,17000
18,119,2026-06-01,East,Neha,Tablet,iPad,4,180000,26000
19,120,2026-06-15,West,Karan,Mobile,Pixel 9,3,210000,30000

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Category')#ye nche output me mean values h jo by default aati h

Category    Laptop    Mobile    Tablet
Region
East       97500.0  210000.0  135000.0
North     107500.0  237500.0  200000.0
South     105000.0  210000.0   80000.0
West      130000.0  185000.0  127500.0

In [7]:
# cross tab
#it is used for counting values
pd.crosstab(df["Region"],df["Category"])

Category  Laptop  Mobile  Tablet
Region
East           2       1       2
North          2       2       1
South          2       2       1
West           1       2       2